
//src/app/layout.js
import { Inter } from "next/font/google";

import '../styles/styles.scss';
import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Create Next App",
    template: '%s - Create Next App'
  },
  description: "Generated by create next app",
  twitter: {
    card: 'summary_large_image'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={inter.className}>
        <div className="wrapper container">
          <Header />
          <main className="main">{children}</main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}

//  https://realfavicongenerator.net/
// https://favicon.io/
